# Generated by Django 2.2.2 on 2019-06-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemachine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeuser',
            name='current_order',
        ),
    ]
