# Generated by Django 2.2.2 on 2019-06-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemachine', '0002_remove_coffeeuser_current_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='coffeemachine.Ingredient'),
        ),
    ]
