# Generated by Django 2.2.2 on 2019-06-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemachine', '0003_auto_20190605_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='orders', to='coffeemachine.Ingredient'),
        ),
    ]
